# Generated by Django 5.2.14 on 2026-06-01 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='autodeskaccount',
            old_name='account',
            new_name='autodesk_user',
        ),
        migrations.RemoveField(
            model_name='autodeskproject',
            name='user',
        ),
        migrations.AddField(
            model_name='autodeskproject',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aps_projects', to='aps_api.autodeskaccount'),
        ),
        migrations.AlterField(
            model_name='autodeskuser',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
