# Generated by Django 5.2.14 on 2026-06-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps_api', '0002_rename_account_autodeskaccount_autodesk_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autodeskaccount',
            name='hub_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='autodeskproject',
            name='hub_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='autodeskproject',
            name='project_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='autodeskuser',
            name='access_token',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='autodeskuser',
            name='refresh_token',
            field=models.TextField(),
        ),
    ]
