# Generated by Django 5.2.14 on 2026-06-02 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps_api', '0003_alter_autodeskaccount_hub_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autodeskproject',
            name='hub_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
