# Generated by Django 5.2.14 on 2026-06-02 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps_api', '0004_autodeskproject_hub_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutodeskSheets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_id', models.CharField(max_length=255)),
                ('sheet_number', models.CharField(max_length=255)),
                ('version_set_id', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aps_api.autodeskproject')),
            ],
        ),
    ]
