# Generated by Django 5.2.14 on 2026-06-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps_api', '0005_autodesksheets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autodesksheets',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
