# Generated by Django 5.2.14 on 2026-06-02 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aps_api', '0006_alter_autodesksheets_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autodesksheets',
            name='status',
        ),
    ]
