# Generated by Django 5.2.14 on 2026-06-03 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps_api', '0007_remove_autodesksheets_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='autodesksheets',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='autodesk_sheets/'),
        ),
    ]
