# Generated by Django 5.2.14 on 2026-06-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps_api', '0008_autodesksheets_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='autodesksheets',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
