# Generated by Django 5.2.14 on 2026-06-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps_api', '0009_autodesksheets_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='autodesksheets',
            name='version',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
