# Generated by Django 5.2.14 on 2026-06-04 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps_api', '0010_autodesksheets_version'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autodesksheets',
            old_name='sheet_id',
            new_name='sheetId',
        ),
        migrations.RenameField(
            model_name='autodesksheets',
            old_name='sheet_number',
            new_name='sheetNumber',
        ),
        migrations.RenameField(
            model_name='autodesksheets',
            old_name='version_set_id',
            new_name='versionSetId',
        ),
        migrations.AddField(
            model_name='autodesksheets',
            name='createdAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autodesksheets',
            name='createdBy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='autodesksheets',
            name='createdByName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='autodesksheets',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='autodesksheets',
            name='deletedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autodesksheets',
            name='deletedBy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='autodesksheets',
            name='deletedByName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='autodesksheets',
            name='updatedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autodesksheets',
            name='updatedBy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='autodesksheets',
            name='updatedByName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
