# Generated by Django 5.2.14 on 2026-06-04 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps_api', '0011_rename_sheet_id_autodesksheets_sheetid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autodesksheets',
            name='deleted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
