# Generated by Django 5.2.14 on 2026-06-04 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps_api', '0012_alter_autodesksheets_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autodesksheets',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
