# Generated by Django 5.2.14 on 2026-06-05 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps_api', '0013_alter_autodesksheets_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autodesksheets',
            old_name='deleted',
            new_name='is_current',
        ),
        migrations.AddField(
            model_name='autodesksheets',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
