# Generated by Django 5.2.14 on 2026-06-05 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aps_api', '0014_rename_deleted_autodesksheets_is_current_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autodesksheets',
            name='is_current',
        ),
        migrations.RemoveField(
            model_name='autodesksheets',
            name='is_deleted',
        ),
    ]
