# Generated by Django 5.2.14 on 2026-06-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps_api', '0015_remove_autodesksheets_is_current_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autodesksheets',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='autodesksheets',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
