# Generated by Django 5.2.14 on 2026-06-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps_api', '0016_autodesksheets_is_current_autodesksheets_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autodesksheets',
            name='is_current',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
