# Generated by Django 5.2.14 on 2026-06-05 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps_api', '0017_alter_autodesksheets_is_current'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('issuanceDate', models.DateTimeField()),
                ('createdAt', models.DateTimeField()),
                ('createdBy', models.CharField(max_length=255)),
                ('createdByName', models.CharField(max_length=255)),
                ('updatedAt', models.DateTimeField()),
                ('updatedBy', models.CharField(max_length=255)),
                ('updatedByName', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='autodesksheets',
            name='versionSetId',
        ),
        migrations.AddField(
            model_name='autodesksheets',
            name='versionSet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aps_api.versionset'),
        ),
    ]
