# Generated by Django 5.2.14 on 2026-06-05 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aps_api', '0018_versionset_remove_autodesksheets_versionsetid_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VersionSet',
            new_name='AutodeskVersionSet',
        ),
    ]
