# Generated by Django 5.2.14 on 2026-06-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps_api', '0019_rename_versionset_autodeskversionset'),
    ]

    operations = [
        migrations.AddField(
            model_name='autodeskversionset',
            name='is_deleted',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='autodeskversionset',
            name='createdAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='autodeskversionset',
            name='createdBy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='autodeskversionset',
            name='createdByName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='autodeskversionset',
            name='updatedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='autodeskversionset',
            name='updatedBy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='autodeskversionset',
            name='updatedByName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
