# Generated by Django 5.2.14 on 2026-06-05 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aps_api', '0020_autodeskversionset_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autodeskversionset',
            name='createdAt',
        ),
        migrations.RemoveField(
            model_name='autodeskversionset',
            name='createdBy',
        ),
        migrations.RemoveField(
            model_name='autodeskversionset',
            name='createdByName',
        ),
        migrations.RemoveField(
            model_name='autodeskversionset',
            name='updatedAt',
        ),
        migrations.RemoveField(
            model_name='autodeskversionset',
            name='updatedBy',
        ),
        migrations.RemoveField(
            model_name='autodeskversionset',
            name='updatedByName',
        ),
    ]
