# Generated by Django 5.2.14 on 2026-06-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps_api', '0021_remove_autodeskversionset_createdat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autodeskversionset',
            name='issuanceDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
