# Generated by Django 4.2.30 on 2026-06-08 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps_api', '0022_alter_autodeskversionset_issuancedate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autodeskversionset',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='autodeskversionset',
            name='createdAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autodeskversionset',
            name='createdBy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='autodeskversionset',
            name='createdByName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='autodeskversionset',
            name='updatedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autodeskversionset',
            name='updatedBy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='autodeskversionset',
            name='updatedByName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
