# Generated by Django 4.2.30 on 2026-06-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps_api', '0023_remove_autodeskversionset_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autodeskversionset',
            name='issuanceDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
