# Generated by Django 4.2.30 on 2026-06-15 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps_api', '0024_alter_autodeskversionset_issuancedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='autodeskproject',
            name='users',
            field=models.ManyToManyField(related_name='projects', to='aps_api.autodeskuser'),
        ),
        migrations.AlterField(
            model_name='autodesksheets',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
    ]
