# Generated by Django 4.2.30 on 2026-06-15 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps_api', '0025_autodeskproject_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autodeskproject',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='projects', to='aps_api.autodeskuser'),
        ),
    ]
