# Generated by Django 4.2.30 on 2026-06-16 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aps_api', '0027_alter_autodeskproject_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autodeskproject',
            name='users',
        ),
        migrations.CreateModel(
            name='AutodeskProjectMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(max_length=30)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('roles', models.JSONField(blank=True, null=True)),
                ('access_levels', models.JSONField(blank=True, null=True)),
                ('added_on', models.DateTimeField(blank=True, null=True)),
                ('products', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('autodesk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aps_api.autodeskuser')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aps_api.autodeskproject')),
            ],
        ),
        migrations.AddField(
            model_name='autodeskproject',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='projects', through='aps_api.AutodeskProjectMembers', to='aps_api.autodeskuser'),
        ),
    ]
