# Generated by Django 4.2.30 on 2026-06-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps_api', '0028_remove_autodeskproject_users_autodeskprojectmembers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autodeskprojectmembers',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
