# Generated by Django 4.2.30 on 2026-06-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps_api', '0029_alter_autodeskprojectmembers_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autodeskuser',
            name='access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='autodeskuser',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
