# Generated by Django 4.2.30 on 2026-06-16 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aps_api', '0030_alter_autodeskuser_access_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autodeskuser',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='autodeskuser',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='autodeskuser',
            name='refresh_token',
        ),
        migrations.AlterField(
            model_name='autodeskprojectmembers',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_members', to='aps_api.autodeskproject'),
        ),
    ]
