# Generated by Django 5.2.15 on 2026-06-17 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps_api', '0031_remove_autodeskuser_access_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutodeskProjectFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=10)),
                ('last_updated_at', models.DateTimeField()),
                ('last_updated_by', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='autodesk_pdf_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_files', to='aps_api.autodeskproject')),
            ],
        ),
    ]
