# Generated by Django 5.2.15 on 2026-06-17 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aps_api', '0032_autodeskprojectfiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autodeskprojectfiles',
            name='last_updated_at',
        ),
        migrations.RemoveField(
            model_name='autodeskprojectfiles',
            name='last_updated_by',
        ),
        migrations.RemoveField(
            model_name='autodeskprojectfiles',
            name='name',
        ),
        migrations.RemoveField(
            model_name='autodeskprojectfiles',
            name='version',
        ),
    ]
