# Generated by Django 5.2.15 on 2026-06-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps_api', '0033_remove_autodeskprojectfiles_last_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autodeskprojectfiles',
            name='created_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='autodeskprojectfiles',
            name='created_by_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='autodeskprojectfiles',
            name='file_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='autodeskprojectfiles',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='autodeskprojectfiles',
            name='updated_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='autodeskprojectfiles',
            name='updated_by_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='autodeskprojectfiles',
            name='version',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
