# Generated by Django 5.2.15 on 2026-06-18 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps_api', '0034_autodeskprojectfiles_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autodeskprojectfiles',
            old_name='created_by',
            new_name='createdBy',
        ),
        migrations.RenameField(
            model_name='autodeskprojectfiles',
            old_name='created_by_name',
            new_name='createdByName',
        ),
        migrations.RenameField(
            model_name='autodeskprojectfiles',
            old_name='updated_by',
            new_name='updatedBy',
        ),
        migrations.RenameField(
            model_name='autodeskprojectfiles',
            old_name='updated_by_name',
            new_name='updatedByName',
        ),
        migrations.AddField(
            model_name='autodeskprojectfiles',
            name='createdAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autodeskprojectfiles',
            name='updatedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
