# Generated by Django 5.2.15 on 2026-06-18 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps_api', '0035_rename_created_by_autodeskprojectfiles_createdby_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autodeskprojectfiles',
            old_name='createdBy',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='autodeskprojectfiles',
            old_name='createdByName',
            new_name='created_by_name',
        ),
        migrations.RenameField(
            model_name='autodeskprojectfiles',
            old_name='updatedBy',
            new_name='updated_by',
        ),
        migrations.RenameField(
            model_name='autodeskprojectfiles',
            old_name='updatedByName',
            new_name='updated_by_name',
        ),
        migrations.RemoveField(
            model_name='autodeskprojectfiles',
            name='createdAt',
        ),
        migrations.RemoveField(
            model_name='autodeskprojectfiles',
            name='updatedAt',
        ),
        migrations.AddField(
            model_name='autodeskprojectfiles',
            name='file_size_bytes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='autodeskprojectfiles',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='autodeskprojectfiles',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autodeskprojectfiles',
            name='createdat',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='autodeskprojectfiles',
            name='updatedat',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
