# Generated by Django 5.2.15 on 2026-06-18 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps_api', '0036_rename_createdby_autodeskprojectfiles_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autodeskprojectfiles',
            name='revision_display_label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
