# Generated by Django 5.2.15 on 2026-06-18 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aps_api', '0037_autodeskprojectfiles_revision_display_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autodeskprojectfiles',
            old_name='version',
            new_name='version_number',
        ),
    ]
