# Generated by Django 5.2.15 on 2026-06-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps_api', '0038_rename_version_autodeskprojectfiles_version_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='autodeskprojectfiles',
            name='current_file_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
