# Generated by Django 5.2.15 on 2026-06-18 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps_api', '0039_autodeskprojectfiles_current_file_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutodeskFileVersions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('version_number', models.CharField(blank=True, max_length=10, null=True)),
                ('revision_display_label', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by_name', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_id', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='autodesk_pdf_files/')),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('createdat', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedat', models.DateTimeField(auto_now=True, null=True)),
                ('autodesk_project_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_versions', to='aps_api.autodeskprojectfiles')),
            ],
        ),
    ]
