# Generated by Django 5.2.15 on 2026-06-18 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps_api', '0041_alter_autodeskfileversions_autodesk_project_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autodeskfileversions',
            name='autodesk_project_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_versions', to='aps_api.autodeskprojectfiles'),
        ),
    ]
