# Generated by Django 5.2.15 on 2026-06-19 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aps_api', '0042_alter_autodeskfileversions_autodesk_project_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autodeskprojectfiles',
            old_name='file_id',
            new_name='item_id',
        ),
    ]
