# Generated by Django 5.2.15 on 2026-06-19 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps_api', '0043_rename_file_id_autodeskprojectfiles_item_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autodeskprojectfiles',
            name='item_id',
        ),
        migrations.AddField(
            model_name='autodeskfileversions',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='autodeskfileversions',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='autodesk_pdf_file/file_versions/'),
        ),
    ]
