# Generated by Django 5.2.15 on 2026-06-19 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aps_api', '0044_remove_autodeskprojectfiles_item_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autodeskfileversions',
            old_name='revision_display_label',
            new_name='version',
        ),
        migrations.RenameField(
            model_name='autodeskprojectfiles',
            old_name='revision_display_label',
            new_name='version',
        ),
    ]
