# Generated by Django 5.2.15 on 2026-06-19 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps_api', '0045_rename_revision_display_label_autodeskfileversions_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autodeskfileversions',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='autodesk_pdf_files/'),
        ),
    ]
