# Generated by Django 5.2.15 on 2026-06-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps_api', '0046_alter_autodeskfileversions_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='autodeskprojectfiles',
            name='item_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
