# Generated by Django 5.2.15 on 2026-06-19 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps_api', '0048_autodeskprojectfolders'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutodeskFolders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_root', models.BooleanField(default=False)),
                ('hidden', models.BooleanField(default=False)),
                ('object_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by_name', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by_name', models.CharField(blank=True, max_length=255, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='aps_api.autodeskfolders')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='aps_api.autodeskproject')),
            ],
        ),
        migrations.DeleteModel(
            name='AutodeskProjectFolders',
        ),
        migrations.AddIndex(
            model_name='autodeskfolders',
            index=models.Index(fields=['folder_id'], name='aps_api_aut_folder__9346f8_idx'),
        ),
    ]
