# Generated by Django 5.2.15 on 2026-06-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps_api', '0049_autodeskfolders_delete_autodeskprojectfolders_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='autodeskfolders',
            name='aps_api_aut_folder__9346f8_idx',
        ),
        migrations.AlterField(
            model_name='autodeskfolders',
            name='folder_id',
            field=models.CharField(max_length=255),
        ),
    ]
