# Generated by Django 5.2.15 on 2026-06-26 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps_api', '0050_remove_autodeskfolders_aps_api_aut_folder__9346f8_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutodeskFolderMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('user_type', models.CharField(max_length=255)),
                ('subject_status', models.CharField(max_length=255)),
                ('subject_type', models.CharField(max_length=255)),
                ('actions', models.JSONField(blank=True, null=True)),
                ('inherit_actions', models.JSONField(blank=True, null=True)),
                ('autodesk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_users', to='aps_api.autodeskuser')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_members', to='aps_api.autodeskfolders')),
            ],
        ),
    ]
