# Generated by Django 5.2.15 on 2026-07-13 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps_api', '0051_autodeskfoldermembers'),
    ]

    operations = [
        migrations.AddField(
            model_name='autodeskprojectfiles',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
