# Generated by Django 5.2.15 on 2026-07-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps_api', '0052_autodeskprojectfiles_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autodeskprojectfiles',
            name='is_deleted',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
