# Generated by Django 5.2.15 on 2026-07-13 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aps_api', '0053_alter_autodeskprojectfiles_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autodeskprojectfiles',
            name='is_deleted',
        ),
    ]
