# Generated by Django 5.2.15 on 2026-07-15 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps_api', '0055_autodeskprojectfiles_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncFolderData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aps_api.autodeskproject')),
            ],
        ),
    ]
