# Generated by Django 5.2.15 on 2026-07-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps_api', '0056_syncfolderdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncfolderdata',
            name='path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
