# Generated by Django 5.2.15 on 2026-07-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps_api', '0057_alter_syncfolderdata_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncfolderdata',
            name='sync_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
