# Generated by Django 5.2.15 on 2026-07-15 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aps_api', '0058_syncfolderdata_sync_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='syncfolderdata',
            old_name='sync_time',
            new_name='last_sync_time',
        ),
    ]
