# Generated by Django 5.2.15 on 2026-07-16 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps_api', '0060_syncfolderdata_sync_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncfolderdata',
            name='sync_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aps_api.autodeskuser'),
        ),
    ]
