# Generated by Django 5.2.15 on 2026-07-16 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps_api', '0061_alter_syncfolderdata_sync_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncfolderdata',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
