# Generated by Django 5.2.15 on 2026-07-16 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps_api', '0062_syncfolderdata_started_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autodeskprojectfiles',
            name='project',
        ),
        migrations.AddField(
            model_name='autodeskprojectfiles',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folder_files', to='aps_api.autodeskfolders'),
        ),
    ]
