# Generated by Django 5.2.15 on 2026-07-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps_api', '0063_remove_autodeskprojectfiles_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syncfolderdata',
            name='started_at',
        ),
        migrations.AddField(
            model_name='syncfolderdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='syncfolderdata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
