# Generated by Django 5.2.15 on 2026-07-21 06:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps_api', '0064_remove_syncfolderdata_started_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileDownloadRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_file_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_file_version_request', to='aps_api.autodeskfileversions')),
                ('scanned_file_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scanned_file_version_request', to='aps_api.autodeskfileversions')),
            ],
        ),
    ]
