# Generated by Django 5.2.15 on 2026-07-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps_api', '0065_filedownloadrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedownloadrequest',
            name='downloaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filedownloadrequest',
            name='is_downloaded',
            field=models.BooleanField(default=False),
        ),
    ]
