# Generated by Django 5.2.15 on 2026-07-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps_api', '0066_filedownloadrequest_downloaded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedownloadrequest',
            name='request_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], max_length=255, null=True),
        ),
    ]
