# Generated by Django 5.2.15 on 2026-07-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps_api', '0067_filedownloadrequest_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedownloadrequest',
            name='request_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=255),
        ),
    ]
