# Generated by Django 5.2.15 on 2026-07-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps_api', '0068_alter_filedownloadrequest_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedownloadrequest',
            name='requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
