# Generated by Django 5.2.15 on 2026-07-21 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aps_api', '0069_filedownloadrequest_requested_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FileDownloadRequest',
            new_name='RequestedVersionLinkRequest',
        ),
    ]
