# Generated by Django 5.2.15 on 2026-07-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps_api', '0070_rename_filedownloadrequest_requestedversionlinkrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestedversionlinkrequest',
            name='request_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('SEND', 'SEND')], default='PENDING', max_length=255),
        ),
    ]
