# Generated by Django 5.2.15 on 2026-07-22 12:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps_api', '0071_alter_requestedversionlinkrequest_request_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestedSheetVersionLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('request_status', models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('SEND', 'SEND')], default='PENDING', max_length=255)),
                ('requested_at', models.DateTimeField(blank=True, null=True)),
                ('is_downloaded', models.BooleanField(default=False)),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_sheet_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_sheet_version_request', to='aps_api.autodesksheets')),
                ('scanned_sheet_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scanned_sheet_version_request', to='aps_api.autodesksheets')),
            ],
        ),
    ]
