# Generated by Django 5.2.15 on 2026-07-22 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aps_api', '0072_requestedsheetversionlink'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RequestedSheetVersionLink',
            new_name='RequestedSheetVersionRequest',
        ),
    ]
