# Generated by Django 5.2.15 on 2026-07-23 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps_api', '0073_rename_requestedsheetversionlink_requestedsheetversionrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('subscription_type', models.CharField(choices=[('Free Trial', 'Free Trial'), ('Basic', 'Basic'), ('Standard', 'Standard'), ('Premium', 'Premium')], max_length=50)),
                ('subscription_term', models.CharField(choices=[('Free Trial', 'Free Trial'), ('Basic', 'Basic'), ('Standard', 'Standard'), ('Premium', 'Premium')], max_length=50)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('total_scans', models.IntegerField(choices=[(10, 10), (30, 30), (50, 50), (100, 100)])),
                ('used_scans', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
