# Generated by Django 5.2.15 on 2026-07-24 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps_api', '0074_subscriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='used_scans',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
