# Generated by Django 5.2.15 on 2026-07-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps_api', '0075_alter_subscriptions_used_scans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='total_scans',
            field=models.IntegerField(blank=True, choices=[(10, 10), (30, 30), (50, 50), (100, 100)], null=True),
        ),
    ]
