# Generated by Django 5.2.15 on 2026-07-24 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps_api', '0076_alter_subscriptions_total_scans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='subscription_term',
            field=models.CharField(choices=[('Free Trial', 'Free Trial'), ('1 Month', '1 Month'), ('6 Month', '6 Month'), ('Yearly', 'Yearly')], max_length=50),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='used_scans',
            field=models.IntegerField(default=0),
        ),
    ]
