# Generated by Django 5.2.14 on 2026-06-01 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='reminder_expired_send',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='reminders',
        ),
    ]
